Fix build on EL9
Node.js 17 and later on EL9 use OpenSSL 3.0, which deprecates and disables certain legacy cryptographic algorithms by default.
The `--openssl-legacy-provider` flag enables legacy cryptographic algorithms in OpenSSL when running Node.js applications.
Without this flag, you may encounter errors such as:

```
Error: error:0308010C:digital envelope routines::unsupported
```

Note that the OpenSSL version on EL8 is 1.1.1. Setting this flag on EL8 may cause the MaxGUI build to fail.